spring:
  application:
    name: clinicos-api

  datasource:
    url: jdbc:postgresql://localhost:5432/clinicos
    username: app_rw
    password: local-dev-only

  flyway:
    user: postgres
    password: local-dev-only

  jooq:
    sql-dialect: postgres

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB

clinicos:
  storage:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: clinicos-attachments

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui

server:
  port: 8080
